"""Pydantic schemas for API request/response models."""

from ies_backend.schemas.block_attribute import (
    BlockAttribute,
    BlockAttributeListResponse,
    BlockAttributeQuery,
    BlockAttributeStats,
    BlockAttributeUpdate,
    BlockAttributeUpdateResponse,
    BlockStatus,
    BlockType,
    EnergyLevel,
    ResonanceSignal,
)
from ies_backend.schemas.context import (
    AreaOfExploration,
    Context,
    ContextCreate,
    ContextCreateRequest,
    ContextCreateResponse,
    ContextJourneyEntry,
    ContextListResponse,
    ContextNoteParseRequest,
    ContextNoteParseResponse,
    ContextSearchRequest,
    ContextSearchResponse,
    ContextSearchResult,
    ContextStatus,
    ContextType,
    ContextUpdate,
    JourneyClassification,
    JourneyEntryCreateRequest,
    JourneyListResponse,
    Question,
    QuestionCreateRequest,
    QuestionListResponse,
    QuestionStatus,
)
from ies_backend.schemas.extraction import (
    ExtractionProfile,
    ExtractionProfileCreate,
    ExtractionResult,
    ExtractionRunRequest,
    ExtractionRunResponse,
    QuestionExtractionProfile,
)
from ies_backend.schemas.passage import (
    PassageRankingRequest,
    PassageRankingResponse,
    RankedPassage,
)
from ies_backend.schemas.visit_tracking import (
    GlobalActivitySummary,
    NewEntity,
    NewHighlight,
    NewItemsDetailRequest,
    NewItemsDetailResponse,
    NewItemsSummary,
    NewQuestion,
    NewRelationship,
    RecordVisitRequest,
    RecordVisitResponse,
    VisitRecord,
    VisitScope,
)
from ies_backend.schemas.session_state import (
    HeartbeatRequest,
    HeartbeatResponse,
    ReadingPosition,
    SessionState,
    SessionStateHistory,
    SessionStateHistoryResponse,
    SessionStateUpdate,
)

__all__ = [
    # Block attribute types
    "BlockAttribute",
    "BlockType",
    "BlockStatus",
    "ResonanceSignal",
    "EnergyLevel",
    "BlockAttributeQuery",
    "BlockAttributeListResponse",
    "BlockAttributeUpdate",
    "BlockAttributeUpdateResponse",
    "BlockAttributeStats",
    # Context types
    "Context",
    "ContextType",
    "ContextStatus",
    "ContextCreate",
    "ContextUpdate",
    "ContextCreateRequest",
    "ContextCreateResponse",
    "ContextListResponse",
    # Question types
    "Question",
    "QuestionStatus",
    "QuestionCreateRequest",
    "QuestionListResponse",
    # Area types
    "AreaOfExploration",
    # Journey types
    "ContextJourneyEntry",
    "JourneyClassification",
    "JourneyEntryCreateRequest",
    "JourneyListResponse",
    # Context Note parsing
    "ContextNoteParseRequest",
    "ContextNoteParseResponse",
    # Context Search
    "ContextSearchRequest",
    "ContextSearchResponse",
    "ContextSearchResult",
    # Extraction types
    "ExtractionProfile",
    "ExtractionProfileCreate",
    "ExtractionResult",
    "ExtractionRunRequest",
    "ExtractionRunResponse",
    "QuestionExtractionProfile",
    # Visit tracking types
    "VisitScope",
    "VisitRecord",
    "RecordVisitRequest",
    "RecordVisitResponse",
    "NewItemsSummary",
    "NewItemsDetailRequest",
    "NewItemsDetailResponse",
    "NewEntity",
    "NewHighlight",
    "NewQuestion",
    "NewRelationship",
    "GlobalActivitySummary",
    # Passage ranking types
    "PassageRankingRequest",
    "PassageRankingResponse",
    "RankedPassage",
    # Session state types
    "ReadingPosition",
    "SessionState",
    "SessionStateUpdate",
    "SessionStateHistory",
    "SessionStateHistoryResponse",
    "HeartbeatRequest",
    "HeartbeatResponse",
]
